apiVersion: apps/v1
kind: Deployment
metadata:
  name: nmlkp
spec:
  selector:
    matchLabels:
      app: nmlkp
  template:
    metadata:
      labels:
        app: nmlkp
    spec:
      containers:
      - name: nmlkp
        image: us-west2-docker.pkg.dev/broncoctf-2023/broncoctf-2023/nmlkp:latest