apiVersion: kustomize.config.k8s.io/v1beta1
kind: kustomization

namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml #ArgoCD install manifest
  - "./backendconfig-argocd-backend-config.yaml"
  - "./frontendconfig-argocd-frontend-config.yaml"
  - "./ingress-argocd.yaml"
  - "./managedcertificate-argocd-tls-cert.yaml"
patchesStrategicMerge:
  - ./configmap-patch.yaml
  - "./service-argocd-server-patch.yaml"