apiVersion: v1
kind: Service
metadata:
  namespace: ctfd
  labels:
    app: ctfd
  name: ctfd
spec:
  ports:
  - name: ui
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ctfd
  type: ClusterIP
status: {}