FROM alpine/socat

#Copy binary to executable location
COPY NMLKP-x86_64-linux .

#Copy flag to working directory
COPY flag.txt .

EXPOSE 1337

CMD [ "tcp-listen:1337,reuseaddr,fork", "EXEC:./NMLKP-x86_64-linux" ]