apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shakespear
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:SCUBroncoSec/BroncoCTF-2023-Internal.git
    targetRevision: HEAD
    path: challenges/Beginner/shakespear-festival/infra
  destination:
    server: https://kubernetes.default.svc