apiVersion: apps/v1
kind: Deployment
metadata:
  name: shakespear
spec:
  selector:
    matchLabels:
      app: shakespear
  template:
    metadata:
      labels:
        app: shakespear
    spec:
      containers:
      - name: shakespear
        image: us-west2-docker.pkg.dev/broncoctf-2023/broncoctf-2023/shakespear:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"