apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-challenges
  namespace: web-challenges
  annotations:
    networking.gke.io/v1beta1.FrontendConfig: web-challenges-frontend-config
    networking.gke.io/managed-certificates: web-challenges-tls-cert
    kubernetes.io/ingress.class: "gce"
  labels:
    name: invisible-captcha
spec:
  rules:
    - host: captcha.web.broncoctf.xyz
      http:
        paths:
          - backend:
              service:
                name: invisible-captcha
                port:
                  number: 3000
            pathType: Prefix
            path: /
    - host: fishy.web.broncoctf.xyz
      http:
        paths:
          - backend:
              service:
                name: a-little-fishy
                number: 80000
            pathType: Prefix
            path: /